name: nlp-hf
channels:
    - nvidia
dependencies:
    # Hugging Face
    - conda-forge::accelerate
    - conda-forge::datasets
    - conda-forge::evaluate
    - conda-forge::transformers
    - huggingface::safetensors

    # Util
    - pytorch::pytorch
    - pytorch::pytorch-cuda=12.1
    - conda-forge::lightning
    - conda-forge::numba

    # Why not?
    # - conda-forge::jaxlib
    # - conda-forge::jax

    # Notebooks
    - jupyterlab
    - ipywidgets

    # Data analysis
    - matplotlib

    - pandas
    - polars
    - scikit-learn
    - scipy
    - numpy

    # Development
    - mypy
    - black
    - python-language-server
    - pyls-black

    # Only available with pip
    - pip
    - pip:
        - lxml
        - bertviz
        - ecco
        - einops

